name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.4.0

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.22.1'

dependencies:
  _flutterfire_internals: ^1.3.40
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  firebase_messaging_platform_interface: ^4.5.42
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.8.0

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
  assets:
    - assets/firebase_msg.js
    - assets/firebase-messaging-sw.js